### ISSUE TITLE
Blur underlaying MapView

### ISSUE THREAD

**Issue by dvcrn** [Kureev/react-native-blur#10]
I'm trying to use this module to add a button on top of my mapview

```
      <View style={styles.container}>
        <MapView
            style={styles.map}
          />
          <VibrancyView
            style={styles.button}
            blurType="light">
              <Text style={styles.buttonText}>Test！</Text>
          </VibrancyView>
      </View>
```

Styles:

```
var styles = StyleSheet.create({
  button: {
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
    position: "absolute",
    bottom: 100,
    width: windowSize.width
  },
  buttonText: {
    color: '#007aff',
    fontFamily: '.HelveticaNeueInterface-MediumP4',
    fontSize: 17,
    fontWeight: 'bold',
    textAlign: 'center',
  },,
  map: {
    flex: 1
  }
});
```

Here's what I get: 

![http://i.imgur.com/X7m58ud.png](http://i.imgur.com/X7m58ud.png)

Any hints what I could be doing wrong?

**Comment by Kureev** [comment]
Seems that you included libraries to xcode project in the wrong way. Please, check readme and your code once again.

**Comment by ms88privat** [comment]
I have kinda the same problem. I tried all different kinds of Imports (e.g. your screenshot) but nothing is working for me with react native 0.8.0 - no errors or whatsoever :(

**Comment by ms88privat** [comment]
Found my mistake... the STYLE of the Blur-View has to implement "backgroundColor: 'transparent'"! Would be good to put this explicit in the docs. Thx for the plugin. Greetings
