### ISSUE TITLE
No manager class found for view with module name "VibrancyView"

### ISSUE THREAD

**Issue by codingjester** [Kureev/react-native-blur#11]
I followed the installation directions in the README and I can't seem to be able to load the required classes for use in my app.

Let me know if there is any extra data I can get you.

**Comment by Kureev** [comment]
It all depends by the way you include folders with library to your project. When adding them, press `Add files to PROJECTNAME`, then instead of creating folder references, choose `Create Groups` and add library. Then, just rebuild your project. Let me know if it helped.

**Comment by codingjester** [comment]
Yep that totally fixed it for me. I had to add the individual files, then grouped them together. Originally, I thought I could just add the folder for the BlurView and that would be fine. Turns out no.

Thanks again!
