### ISSUE TITLE
Doesn't work with React Native 0.5

### ISSUE THREAD

**Issue by gpbl** [Kureev/react-native-blur#13]
I'm trying to make react-native-blur working with react-native 0.5 but the only thing I get is a red border around the text:

```js
        <View style={styles.container}>
          <Image source={require("image!background")}>
            <BlurView blurType="light">
              <Text>Hi, I am a tiny menu item</Text>
            </BlurView>
          </Image>
      </View>
```

To try it, i changed package.json [in my fork](https://github.com/gpbl/react-native-blur/blob/master/package.json) specifying `"react-native": "^0.5.x"` as peer dependency. Any idea?

**Comment by Kureev** [comment]
Hi there! I haven't tried yet for `0.5.*` yet, it seems soon we'll get a `0.6.0` version, so when it's gonna be released, I'll take a look on patching existing component to align to it. Maybe it'll be interesting field for PR for @alinz ?

**Comment by gpbl** [comment]
Thanks! ...with the [two-weeks release schedule](http://facebook.github.io/react/blog/2015/05/22/react-native-release-process.html), as 0.6 is out we will get 0.7 soon as well :smile: 

I don't get the versioning of this module: on npm is `0.5.0`, but master [has] (https://github.com/Kureev/react-native-blur/blob/master/package.json#L3) `0.4.2` and the example [uses](https://github.com/Kureev/react-native-blur/blob/master/examples/basic/package.json#L10) `0.3.0`. I tried all before reporting the issue!

PS. I'd keep react-native as peer dependency, or user may risk to install multiple react-native versions.

**Comment by Kureev** [comment]
Yeah, sorry for this misaligning with versioning, need some time to clean it up. That was a really tough weekend on [Startup Weekend Amsterdam](http://startupweekend.org/), had no time to take a look into it. 
By the way, a good point about keeping react as a peer dependency, I think we need to do it!

**Comment by alinz** [comment]
@Kureev, I was excited to fix the bug. However, it seems to work perfectly fine with me :(  I don't see any problem with 0.5.0. Also based on release note there are not any major breaking changes into the frame work [release notes](https://github.com/facebook/react-native/releases).

@gpbl can you also check couple of things?
1: create a brand new project with react-native 0.5.0
2: added those two folders into the project
3: copy the example index.ios.js into your project
4: clean the entire project and re build it
5: remove node_modules folder inside `react-native-blur` and change the dependencies to 0.5.0 and do the `npm install` again.

if you do that and nothing happen, let me know and I will provide you an example for 0.5.0.

**Comment by Kureev** [comment]
Hm, mb we anyway need to update dependency versions in example folder and generic folder itself. Also, would be handy to include react-native as a peerDependency instead of dependency now

**Comment by gpbl** [comment]
Thanks guys for the help, i could get it working. After trying again, I can confirm my problem was not related with the react-native version. When adding the file, i had "Create folder references" instead of "Create groups" enabled:

![screen shot 2015-06-08 at 09 15 07](https://cloud.githubusercontent.com/assets/120693/8029558/f154a25a-0dbe-11e5-9620-e37484efa649.png)

It seems React Native adds a red border around components that are not referring correctly to the sources. Phew! Thanks again!

**Comment by gpbl** [comment]
Anyway, I'd send a PR with the `peerDependencies` but it seems the version on master is not in sync with that on npm, so I better wait for an aligned repo...

**Comment by alinz** [comment]
@gpbl are you going to provide PR for this? I really need this.

**Comment by gpbl** [comment]
@alinz sure, #15 should make it !

**Comment by alinz** [comment]
@gpbl, Awesome! Thanks.
@Kureev, waiting for your approval :P

**Comment by Kureev** [comment]
Approved <3 Thanks!
