### ISSUE TITLE
Support for React 0.6.0-rc

### ISSUE THREAD

**Issue by cyprusglobe** [Kureev/react-native-blur#16]
When will support for 0.6.0 be out?

**Comment by Kureev** [comment]
Gonna take a look today

**Comment by cyprusglobe** [comment]
@Kureev Thanks

**Comment by Kureev** [comment]
Sorry for that, I was really busy on my primary job. `0.5.3` has been released!

**Comment by cyprusglobe** [comment]
Thanks so much @Kureev
