### ISSUE TITLE
Gamma differences between simulator and iphone?

### ISSUE THREAD

**Issue by aherasimchuk** [Kureev/react-native-blur#17]
When using react-native-blur, the effects rendered in the iOS simulator appear correct, but when built on the iphone itself, are a degree of magnitude darker as if the gamma were cranked down. Is this a known issue, or am I missing something?

**Comment by Kureev** [comment]
I think it's more related to the matrix you use in your desktop/laptop and mobile device. If you'll use retina screen for simulator, you'll have the same colors.
