### ISSUE TITLE
React Native 0.8.0

### ISSUE THREAD

**Issue by jaysalvat** [Kureev/react-native-blur#18]
Hello and thanks!

Is there a React Native 0.8.0 compatible version out there?
Impossible to make it work for me. Do I miss something?

Thanks a lot.

**Comment by Kureev** [comment]
Haven't tested on 0.8.0, can you show me a stack trace? I guess it's related to `requireNativeComponent`, probably it's missing now

**Comment by Kureev** [comment]
Unfortunately, due to lack of docs about changes in `0.8.0`, it's hard to make five-minutes fix for that. 
So now it *oficially* supports latest stable build `0.7.1`. If you want to help, you may check what's the way to create native components in `0.8.0` and tell me - I'll create a `0.8.0` branch

**Comment by jaysalvat** [comment]
Hello.

I have no error. No blur, just a weird red box where the blur should takes place.

Unfortunately, I have absolutely no knowledge in Native module to help you.
I certainly missing something simple. I don't know what.

**Comment by jaysalvat** [comment]
I've just made a fresh 0.7.1 project.
Here the result.

![capture d ecran 2015-07-20 a 16 43 33](https://cloud.githubusercontent.com/assets/55496/8778477/84569aee-2efe-11e5-8845-75bae2d985dd.png)

**Comment by Kureev** [comment]
It seems you're not following README :wink: 
When you create a project, you need to include `obj-c` libraries `RNBlur` and `RNVibrancy`. After that, it will work.

**Comment by jaysalvat** [comment]
Yes I did :)

    In the XCode's "Project navigator", right click on project's name ➜ Add Files to <...>
    Go to node_modules ➜ react-native-blur ➜ add RNBlur and RNVibrancy folders

**Comment by jaysalvat** [comment]
![capture d ecran 2015-07-20 a 17 47 17](https://cloud.githubusercontent.com/assets/55496/8780154/69cc41de-2f07-11e5-91f9-83954a078985.png)

Is this the right place?

**Comment by tsunammis** [comment]
I have the same issue with RN 0.7.x

```
Warning: Native component for "BlurView" does not exist
Warning: Native component for "VibrancyView" does not exist
```

All steps inside the setup process have been executed.

Best,

**Comment by Kureev** [comment]
![image](https://cloud.githubusercontent.com/assets/2273613/8785102/b64460d2-2f25-11e5-8ec1-912e9a6e0bc8.png)

Sure you have this settings while import?

**Comment by jaysalvat** [comment]
@Kureev Great! It works!

You should add it to the README :)

**Comment by Kureev** [comment]
Seems so, it's already 2-3rd issue about it

**Comment by jaysalvat** [comment]
Thanks a lot.

It might be time to update package.json and make it 0.8.0 compatible. It works perfectly.

**Comment by tsunammis** [comment]
It works fine :) Good job !!

**Comment by akd6162** [comment]
I got same Problem for Android

**Comment by Kureev** [comment]
@akd6162 you use 0.8.0 as well?

**Comment by akd6162** [comment]
No,  react-native 1.0.1

**Comment by akd6162** [comment]
but I got a warning missing Native component for BlurView

**Comment by Kureev** [comment]
Then I'd recommend you to create a new issue for this problem then. I think people in this thread don't want to be notified about it.

P.S. I think you're wrong about your RN version, because the latest one is 0.30.0

**Comment by akd6162** [comment]
How can I find  Version of RN which I am using

**Comment by Kureev** [comment]
@akd6162 `npm list | grep react-native` or check your `package.json`.

**Comment by roysG** [comment]
@Kureev, I have also the error that component not found, how do you get the screen you picture?

**Comment by roysG** [comment]
I am using in react native version 0.33.0, 
I also did rnpm link and update the target version deploy to 8.2, but i get the same error on component not found.
I checked in iphone

**Comment by binchik** [comment]
I have the same issue with react-native 0.37

**Comment by Kureev** [comment]
Something is wrong with the linkage process. Try to make it manually

**Comment by binchik** [comment]
@Kureev thanks, I cleaned the project, removed DerivedData and it worked!
