### ISSUE TITLE
Not blurring entire image

### ISSUE THREAD

**Issue by klippx** [Kureev/react-native-blur#188]
We found a small issue while using this library, and it exists also in the Basic demo provided by you guys.

Please see the attached screenshot, the blurring misses 2px at the bottom. We had to fix this by introducing `{ bottom: -2 }` in `styles.image`.

Best regards!

![screenshot_1492591220](https://cloud.githubusercontent.com/assets/2785359/25171148/1a1db446-24ed-11e7-8c61-7b812bfc9bfa.png)

**Comment by ndbroadbent** [comment]
Hi @klippx, I've also noticed this. It's a bug in the RenderScript API on Android, and [the original 500px blurring library had a workaround](https://github.com/500px/500px-android-blur/issues/7), but it didn't always work for all screen resolutions. It would be great to figure out how to blur the entire image on all sizes. For now, I would recommend just using the `bottom: -2` workaround.
