### ISSUE TITLE
Blur child

### ISSUE THREAD

**Issue by maxs15** [Kureev/react-native-blur#19]
Hi @Kureev,

Would it be possible to blur the childs of the BlurView ?
I'm asking you that question because of [react-native-video](https://github.com/brentvatne/react-native-video), the Video component doesn't support subviews so no way to apply a blur filter currently...
Any idea ?

Thanks

**Comment by Kureev** [comment]
Blur view in iOS AFAIK supports only this way of applying. I think that the best solution in your case is to write native blur filter and apply it to the video. Unfortunately, my component couldn't help you with this.

**Comment by maxs15** [comment]
Okay I see, thanks for the details :+1:
