### ISSUE TITLE
React Native 0.10.0-rc 

### ISSUE THREAD

**Issue by ms88privat** [Kureev/react-native-blur#20]
Breaking change:

https://github.com/facebook/react-native/issues/2347#issuecomment-131598769

**Comment by dubert** [comment]
:+1:

**Comment by Kureev** [comment]
I'll make it when 0.10.0 would become `stable` release. Otherwise it breaks latest stable (`0.9.0`) release

**Comment by booxood** [comment]
Mark

**Comment by dubert** [comment]
ETA?

**Comment by Kureev** [comment]
ETA 30.08

**Comment by nautical** [comment]
:+1:

**Comment by Kureev** [comment]
Why we need to support `0.10.0-rc` if `0.10.0` is out?

**Comment by berkcaputcu** [comment]
isn't it broken for `0.10.0` as well?

**Comment by smothers** [comment]
:+1:

**Comment by Kureev** [comment]
@smothers have you checked it? Everything is fine?

**Comment by Kureev** [comment]
just fyi: fixed in `0.6.1`
