### ISSUE TITLE
Please provide xcodeproj file in NPM module

### ISSUE THREAD

**Issue by jhabdas** [Kureev/react-native-blur#22]
Looking forward to using this though this is the first native module I've come across recently which didn't have a `xcodeproj` file checked in - which is what most people expect right now. It would be nice to have the installation consistency of other modules in this one as well.

For example please see [react-native-video](https://github.com/brentvatne/react-native-video). Thanks!

**Comment by Kureev** [comment]
Hm, sounds good, gonna implement it asap

**Comment by Kureev** [comment]
Done, `0.7.1` contains `ios/RNBlur` project.

**Comment by jhabdas** [comment]
Thanks, @Kureev!

**Comment by Kureev** [comment]
haha, first check if it works :wink:
