### ISSUE TITLE
red outline

### ISSUE THREAD

**Issue by kevtastic** [Kureev/react-native-blur#24]
blur view is positioned right and sized properly but all that shows up is a red outline of the view. I also attempted to use it as the child of a standard Image tag and it didnt work..

**Comment by olivierlesnicki** [comment]
@kevtastic did you do this step correctly: https://github.com/Kureev/react-native-blur#installation
It seems you haven't imported the objective C in your project correctly, or maybe you need to rebuild it.

**Comment by kevtastic** [comment]
@olivierlesnicki i actually went back and did that again and realized my error was being caused by adding the vibrancy folder to my project.

I removed that completely and BlurView works now.

**Comment by pukhalski** [comment]
Same issue for me as well.

**Comment by Kureev** [comment]
@kevtastic @pukhalski I haven't checked `0.11.0` yet, but just to be sure, have you added both `RNBlur` and `RNVibrancy` folders to your project as it's shown [there](https://cloud.githubusercontent.com/assets/2273613/8785102/b64460d2-2f25-11e5-8ec1-912e9a6e0bc8.png)?

**Comment by kevtastic** [comment]
@Kureev 

yup, they both appear to be added correctly but I still get errors.

I also updated my react native to 0.12.0-rc and am getting another error inside of xcode.

>Warning: Native component for "VibrancyView" does not exist

is a javascript error, while using 0.12.0-rc im also getting this xcode error

![error](http://imgur.com/N9bwybF.png)

**Comment by Kureev** [comment]
@kevtastic @pukhalski So, I rebuilt everything for `0.11`+. Now you need to follow different way including `RNBlur` to your project. Take a look on README.md, installation part. That will solve the problem.

**Comment by kevtastic** [comment]
i removed everything and reinstalled the package, but now im actually still getting the same error.

plus another one in the library

![error](http://i.imgur.com/bXk7pbx.png)

**Comment by Kureev** [comment]
@kevtastic which version of RN you use? 0.11+? Also, make sure `Build Settings` -> `Search Paths` -> `Header Search Paths` looks like
![image](https://cloud.githubusercontent.com/assets/2273613/10296380/56e921f6-6bc8-11e5-9598-bb11b52c0680.png) 
or something like it. 

Also as I see you're using scaffolded tests, please, remove them from final build.

**Comment by kevtastic** [comment]
@Kureev 
i removed the testing and made sure my search paths were good but it looks like im still getting the same errors

![error](http://i.imgur.com/UQIeoJp.png)

sorry for all the trouble

**Comment by kevtastic** [comment]
Ignore that! I was able to remove those errors with a second rebuild of the package and reinstall!

i have another error now but I'm assuming it's on my end so dont worry about it. Will post a response for others once i figure out whats wrong here.

![error](http://imgur.com/8nNNQoA.png)

**Comment by Kureev** [comment]
^ That happens because you replaced RNBlur or something, re-plug it and that should work

**Comment by kevtastic** [comment]
i got rid off al the errors but I'm getting the same red line along with javascript errors

Warning: Native component for "BlurView" does not exist 
Warning: Native component for "VibrancyView" does not exist

**Comment by Kureev** [comment]
Seems you haven't included `RNBlur.xcodeproj` to your project or/and haven't added it to build phase

**Comment by kevtastic** [comment]
was finally able to solve everything by taking header search paths from an existing library i had installed and copying them over to RNBlur.

though i had to modify the path to compensate for difference in the location of the library's xcodeproject

**Comment by Kureev** [comment]
Glad you figured out :+1:
