### ISSUE TITLE
borderRadius doesn't work

### ISSUE THREAD

**Issue by olivierlesnicki** [Kureev/react-native-blur#25]
It seems I'm unable to configure borderRadius on VibrancyView and BlurViews

**Comment by Kureev** [comment]
I've just tried on `example/Basic` by adding `borderRadius: 100` to it. 

![image](https://cloud.githubusercontent.com/assets/2273613/10295482/3856fad0-6bc1-11e5-9330-122399aa9193.png)

LGTM, so doesn't seems to be an issue. If you have any *questions*, please, contact me via slack (kureev on #reactiflux) or @kureevalexey on twitter, I would be glad to help.
