### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by olivierlesnicki** [Kureev/react-native-blur#26]
The latest version of react-native-blur breaks the build with the following reason:
`#import "RCTComponent.h" file not found`

**Comment by zperrault** [comment]
I am having this issue as well. Haven't been able to figure out what's wrong/

**Comment by Kureev** [comment]
@olivierlesnicki @zperrault Have you added `RNBlur` to your's app `Build Phases`

**Comment by JeanLebrument** [comment]
I having the same issue. 

`RNBlur` is well added in `Build Phases` on the latest position.

**Comment by meznaric** [comment]
I'm having the same problem.
Part of the solution may be the last comment in https://github.com/Kureev/react-native-blur/issues/24 . If anyone figures the whole thing - please share.

**Comment by Kureev** [comment]
As a quick hotfix, you can include .m and .h files directly, by adding them to project. But fixing this is a 🔝 prio for me now

**Comment by dubert** [comment]
I am also having this issue. Double checked and followed every step.

**Comment by Kureev** [comment]
Please, check `0.7.2` version.

**Comment by dubert** [comment]
@Kureev just attempted with 0.7.2

I'm getting:
<img width="1016" alt="screen shot 2015-10-08 at 12 11 36" src="https://cloud.githubusercontent.com/assets/1843672/10372469/e21293ae-6db5-11e5-94b8-563e6697d585.png">
With a red outline around the area meant to be blurred

**Comment by Kureev** [comment]
Ill check it in 30 mins. But it looks like you havent linked them properly

**Comment by zperrault** [comment]
@Kureev I have `RNBlur` in my Build Phases. Looks like it is some sort of issue with header search paths.

**Comment by dubert** [comment]
You're right. I linked them properly and the build fails again.

**Comment by Kureev** [comment]
Investigating it right now, w8 a bit

**Comment by Kureev** [comment]
@dubert I've just tried it and that worked for me. So I suggest to debug it together. First of all I have a bunch of questions:
- Which RN version you're running?
- Have you tried to run an example from `examples/Basic` folder?
- You added project to Libraries, then added it to Build Phases, then cleaned up build (cmd-shift-k) and tried to build, right?

**Comment by Kureev** [comment]
Ok, I feel really sorry about this bug, we finally managed to fix it. It was a super stupid mistake from my side: I missed extra "../" in the path. Now should be fine. `0.7.3`

**Comment by dubert** [comment]
It works!

**Comment by Kureev** [comment]
![image](http://static1.gamespot.com/uploads/scale_super/84/842138/2914446-7697884428-giphy.gif)

**Comment by dubert** [comment]
Thanks for your hard work :)

**Comment by meznaric** [comment]
Thanks!

**Comment by JeanLebrument** [comment]
Thanks for the great work @Kureev ! :+1:

**Comment by jeangui** [comment]
Hi,

I have the same error but I don't understand what I should do. I have git clone the latest version of the repository. Should I change path somewhere in the Xcode Project as well ?

Thanks 

Best 

Jeangui

**Comment by Kureev** [comment]
Have you followed the README instructions, @jeangui?

**Comment by jeangui** [comment]
Hi
I did follow the "usage example" chapter.
Should i need to add the Blur library for the sample as well ? Sorry for this newbie question ...
Jeangui

**Comment by Kureev** [comment]
No probs! I'm here to help. If you're sure you propperly linked native libs/included xcodeproj from node_modules, then I need a version number of RN you're using

**Comment by jeangui** [comment]
Ok. thanks for the help. I gonna test tonight. I will let you know.

Best
jeangui
