### ISSUE TITLE
support react-native 0.12.x?

### ISSUE THREAD

**Issue by yorkie** [Kureev/react-native-blur#27]
When installing with react-natinve@0.12.0, I got the messages below:

```
The package react-native@0.12.0 does not satisfy its siblings' peerDependencies requirements!
```

Could we support 0.12.x now? Is there any known issue about this?

/cc @Kureev

**Comment by arianitu** [comment]
Any update on this?

**Comment by Kureev** [comment]
Done. Will bump npm version as soon as I will reach my Mac

**Comment by Kureev** [comment]
`0.7.4` solve this issue

**Comment by yorkie** [comment]
Thank you @Kureev
