### ISSUE TITLE
Creates too many subviews

### ISSUE THREAD

**Issue by brentvatne** [Kureev/react-native-blur#3]
![bug](http://url.brentvatne.ca/1gh6d.png)

This seems to be because we add the effect in `layoutSubviews` and don't clean up after any previously created ones - I think we should use `setBlurType` to create it instead, and make sure to remove the previously created subview when we change it.

If I add this before creating the visual effect view:
```
  [visualEffectView removeFromSuperView];
```

It cleans up properly and we get the right number of layers, *but* we are still creating a bunch and deleting them, and thrashing leads to performance problems.

**Comment by brentvatne** [comment]
Ah @Kureev you patched this with 0.40, thanks :smile:

**Comment by Kureev** [comment]
@brentvatne 😉
