### ISSUE TITLE
Does it blur everything?

### ISSUE THREAD

**Issue by strazi** [Kureev/react-native-blur#4]
Forgive my ignorance, but should these effects blur everything underneath them? Or does it only blur images?

For example, if I have a page of text, and then put this element on top of it, should I expect a blur?

**Comment by Kureev** [comment]
It should blur everything in parent views. Please, let me know if it doesn't work like this.

**Comment by strazi** [comment]
I got this working. There are two options when adding folders in XCode, `Create groups` and `Create folder references`. Apparently `Create groups` is required to get this working. Thanks for the plugin!

**Comment by Kureev** [comment]
I'm glad you found it useful!

**Comment by Kariko** [comment]
@Kureev what should i do to blur  a View?
