### ISSUE TITLE
Blur view background stops updating

### ISSUE THREAD

**Issue by canpoyrazoglu** [Kureev/react-native-blur#400]
I'm using BlurView 3.6.0, React Native 0.63.3 and iOS 14 and my blur view's background is not updating after, say, the view in the background moves out of the view. I can see the last frame static (blurred) in the background of the blur view, but as long as the background view doesn't move back into the view, I don't see it being updated. This is the case both on simulator and device.

Why would this be happening?

**Comment by canpoyrazoglu** [comment]
I found out the reason, though don't know why it's happening:

The blur view was inside an `Animated.View` which had its opacity animated like:

```
  <Animated.View style={[
          opacity: this.state.scrollOffset.interpolate({
          inputRange: [20, 36],
          outputRange: [0, 1],
          extrapolate: 'clamp'
                        })}]}>
                            {
                                this.theme == 'dark' ? <BlurBackground blurType='dark' style={StyleSheet.absoluteFillObject}/> : <View style={style.lightHeader}/>
                            }
 [...]
```

I was playing with the values and when I changed `extrapolate` to `identity` instead of `clamp`, it started working properly.

**Comment by Kureev** [comment]
I'm not sure if the issue still stands or should we close it as "resolved"?
