### ISSUE TITLE
Flatlist background blur? 

### ISSUE THREAD

**Issue by C-odes** [Kureev/react-native-blur#412]
Hey guys. So I have a flatlist with a view within it. 

I could put blur on the view within, however that would make each row blurry. That's not what I want.

What I want is the flatlist itself to be blurry. 

Because the blacklist has a background color of white with opacity at 0.7. And I want the backgroundimage underneath to be blurred. 

Not the rows within the flatlist that have space between them 
How do we fix that?

**Comment by parthya** [comment]
Did you fix this?
