### ISSUE TITLE
Do you have plan to remove jcenter?

### ISSUE THREAD

**Issue by jihokim2** [Kureev/react-native-blur#434]
react-native 0.65 will support mavencentral. Bintray (incl. JCenter) shutdown on May 1st.

**Comment by jpudysz** [comment]
+1 Library doesn't work with React Native 0.65.0+

**Comment by kanzitelli** [comment]
@jihokim2 @jpudysz you can check the solution here #444

**Comment by idrissakhi** [comment]
i have re-written the lib to work correctly on new RN version => https://www.npmjs.com/package/rn-id-blurview
need some support so the react community take it to replace this package that seems to not be maintained anymore

**Comment by Titozzz** [comment]
Fixed in 4.0.0
