### ISSUE TITLE
android

### ISSUE THREAD

**Issue by wq13718048209** [Kureev/react-native-blur#449]
My RN version is 0.65, and it doesn't work on Android:
Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.github.Dimezis:BlurView:version-1.6.6.
     Required by:
         project :app > project :react-native-community_blur
      > Could not resolve com.github.Dimezis:BlurView:version-1.6.6.
         > Could not get resource 'https://www.jitpack.io/com/github/Dimezis/BlurView/version-1.6.6/BlurView-version-1.6.6.pom'.
            > Could not HEAD 'https://www.jitpack.io/com/github/Dimezis/BlurView/version-1.6.6/BlurView-version-1.6.6.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/6.9/userguide/build_environment.html#gradle_system_properties
                  > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

I have modified it according to #444, but it still cannot run normally on Android

**Comment by prakashkrsingh0** [comment]
it is not working with the camera on android. but it is working on ios, other screens of android also.

**Comment by najam-falcon** [comment]
I am also facing same issue, did you solved it? @wq13718048209

**Comment by idrissakhi** [comment]
i have re-written the lib to work correctly on new RN version => https://www.npmjs.com/package/rn-id-blurview
need some support so the react community take it to replace this package that seems to not be maintained anymore

**Comment by Titozzz** [comment]
Fixed in 4.0.0

**Comment by olive49** [comment]
testing 4.0.0 now but still no blur, what RN version do you have @Titozzz ?

**Comment by Titozzz** [comment]
@olive49 Are you positioning the blurView in 'absolute' above something ?

**Comment by olive49** [comment]
@Titozzz yes it is with absolute positioning above the camera
