### ISSUE TITLE
Still being maintained?

### ISSUE THREAD

**Issue by mstiggle** [Kureev/react-native-blur#459]
Hey, I have an issue that it seems many are having, with no move to resolve it. Does this library still see regular maintenance? Looks like the last commit was over a year ago. 

@Kureev Do you need contributors? It seems according to #444 that there are people willing to help!

I really need to be able to change the `overlayColor` so that I can control what the blur looks like on iOS and android. I also need to control the `blurAmount`. Unfortunately, `blurAmount` only has an effect if you have `blurType` set to `light` or `xlight`. You can see other issues asking for a solution to this in #331 and #421 

Is anyone aware of a different react native blur library that will allow you to control the blur amount and color?

**Comment by mjm918** [comment]
did you manage to find any alternative library? it seems this lib is dead

**Comment by LautaroNavarro** [comment]
I'm also searching for alternative libraries

**Comment by idrissakhi** [comment]
i have re-written the lib to work correctly on new RN version => https://www.npmjs.com/package/rn-id-blurview
need some support so the react community take it to replace this package that seems to not be maintained anymore

**Comment by ParsaNasirimehr** [comment]
@idrissakhi how about discussing it in the working group for the new arch?https://github.com/reactwg/react-native-new-architecture

**Comment by Titozzz** [comment]
👋🏻 I asked Alexey for permissions and the repo, we are back to life 😎
