### ISSUE TITLE
ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'

### ISSUE THREAD

**Issue by lxdaixin128** [Kureev/react-native-blur#470]
warning generate from react-native  0.68.1

**Comment by KieQuang** [comment]
@maheshwarimrinal Do you have any plan to fix?

**Comment by maheshwarimrinal** [comment]
PR #466 closes this issue

**Comment by idrissakhi** [comment]
i have re-written the lib to work correctly on new RN version => https://www.npmjs.com/package/rn-id-blurview
need some support so the react community take it to replace this package that seems to not be maintained anymore

**Comment by KieQuang** [comment]
@maheshwarimrinal 3.6.0 still get issue did u sure u fix it???

**Comment by idrissakhi** [comment]
@KieQuang i have re-written the lib to work correctly on new RN version => https://www.npmjs.com/package/rn-id-blurview
need some support so the react community take it to replace this package that seems to not be maintained anymore

try it it solves this issue

**Comment by maheshwarimrinal** [comment]
> @KieQuang i have re-written the lib to work correctly on new RN version => https://www.npmjs.com/package/rn-id-blurview need some support so the react community take it to replace this package that seems to not be maintained anymore
> 
> try it it solves this issue

I haven't fixed it, as someone has already opened the PR, I thought it's fixed. Currently I don't have enough bandwidth for the same or I can try on weekend

**Comment by KieQuang** [comment]
@idrissakhi i try use your lib but still got issues.

**Comment by KieQuang** [comment]
@maheshwarimrinal Before you fix i will use local. Pls notice me when it fixed. Thanks you so much
.

**Comment by faroutchris** [comment]
This is an issue that currently breaks apps on React Native 0.69.

`ERROR  Invariant Violation: ViewPropTypes **has been removed** from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.`

**Comment by idrissakhi** [comment]
@KieQuang have you tried the last version of my lib ? It's working fine, and it does not contain ViewPropTypes, so it should work as expected on 0.69

**Comment by KieQuang** [comment]
> @KieQuang have you tried the last version of my lib ? It's working fine, and it does not contain ViewPropTypes, so it should work as expected on 0.69

Btw thank you i will check later.

**Comment by YanislavSpaceIQ** [comment]
here is typescript migration PR that fixes this issue. if you need it:  https://github.com/Kureev/react-native-blur/pull/473

**Comment by stage88** [comment]
@KieQuang Can we please look at merging #473.

**Comment by faroutchris** [comment]
It's pretty clear this library is abandoned. Seems that it's a good idea to migrate to https://www.npmjs.com/package/rn-id-blurview or roll your own implementation.

**Comment by KieQuang** [comment]
@stage88 thank great work !!!

**Comment by Titozzz** [comment]
Fixed !
