### ISSUE TITLE
Android Blur View is not latest

### ISSUE THREAD

**Issue by informsharique** [Kureev/react-native-blur#477]
So, I can see that the BlurView from Dimezis is last releases version is 2.0.2 but you're using more than a year old version i.e. 1.6.6 and it has fixed quite some bugs and addressed support on Android 12 APIs.
By any means, is there any chance we'll be getting the newer library Integrated or is there any limitations integrating this?

**Comment by jcdhlzq** [comment]
Mark

**Comment by Titozzz** [comment]
Yep I can probably update that, let me check if there are any breaking changes

**Comment by Titozzz** [comment]
@informsharique Can you test 4.1.0 😄 ?

**Comment by informsharique** [comment]
Sure thing, I'll test it by this weekend and let you know if I find any issues. Thanks a lot!! 😃
