### ISSUE TITLE
Duplicate class eightbitlab.com.blurview.BlurAlgorithm

### ISSUE THREAD

**Issue by bulkinav** [Kureev/react-native-blur#479]
Hello,

I trying build project with the latest version [4.1.0](https://github.com/react-native-community/react-native-blur/compare/v4.0.0...v4.1.0) in Android Studio and get an error: 

`Duplicate class eightbitlab.com.blurview.BlurAlgorithm found in modules jetified-BlurView-version-2.0.2-runtime (com.github.Dimezis:BlurView:version-2.0.2) and jetified-blurview-1.6.6-runtime (com.eightbitlab:blurview:1.6.6)`

**Comment by Titozzz** [comment]
Can you try ./gradlew clean inside android folder and rebuild the app ?

**Comment by bulkinav** [comment]
Of course, I did it (Clean / Rebuild), but still gets this error.
And no problem with version 3.3.0

gradle: 6.9.1
gradle plugin: 4.2.2

Environment:

System:
    OS: macOS 12.4
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 29.95 MB / 24.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.5.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0
      System Images: android-22 | Google APIs Intel x86 Atom_64, android-28 | Android TV Intel x86 Atom, android-30 | Intel x86 Atom_64, android-30 | Google TV Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Chipmunk 2021.2.1 Patch 1 Chipmunk 2021.2.1 Patch 1
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_312 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.67.4 => 0.67.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by Titozzz** [comment]
Did you have a patch package or something done to get 3.3 working that you kept ? Like a custom blurview version or something ?

Please try to reproduce in a fresh new project and let me know

**Comment by bulkinav** [comment]
@Titozzz I found the reason for this behavior. This is problem on "react-native-bottom-sheet" side: https://github.com/gorhom/react-native-bottom-sheet/issues/1037

**Comment by Titozzz** [comment]
Closing here then

**Comment by freemanUA** [comment]
same problem
