### ISSUE TITLE
Support Fabric

### ISSUE THREAD

**Issue by andresribeiro** [Kureev/react-native-blur#487]
Are there any plans to support Fabric?

**Comment by gispada** [comment]
Hi, I have started the migration to Fabric Components, while still keeping the library compatible with the old architecture. Currently working on iOS...

**Comment by devoren** [comment]
@gispada Hello, have you tried this in 0.71 on Android? I have a problem with the new arch

**Comment by CodingWithNobody** [comment]
This will help https://www.youtube.com/watch?v=qSlnZHPFxfk
