### ISSUE TITLE
Could not resolve com.github.Dimezis:BlurView:version-2.0.2.

### ISSUE THREAD

**Issue by wouterds** [Kureev/react-native-blur#518]
**1) Library version**
`@react-native-community/blur ^4.3.0`

**2) Device and OS version**
Android 12 emulator

**3) Detailed steps to reproduce the issue**
`yarn android`

**4) XML layout and code for BlurView setup**
Unrelated

**5) Stacktrace in case of a crash**
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-community_blur:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-community_blur:debugCompileClasspath'.
   > Could not resolve com.github.Dimezis:BlurView:version-2.0.2.
     Required by:
         project :react-native-community_blur
      > Skipped due to earlier error
      > Skipped due to earlier error
```

I'm not sure if this is an issue with Jitpack or something went wrong during publishing?

**Comment by wouterds** [comment]
Now I keep getting this

```
* What went wrong:
Could not determine the dependencies of task ':app:mergeDevDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:devDebugRuntimeClasspath'.
   > Could not resolve com.github.Dimezis:BlurView:version-2.0.2.
     Required by:
         project :app > project :react-native-community_blur
      > Could not resolve com.github.Dimezis:BlurView:version-2.0.2.
         > Could not get resource 'https://www.jitpack.io/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'.
            > Could not GET 'https://www.jitpack.io/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'. Received status code 521 from server: 
```

**Comment by SGamrekelashvili** [comment]
I Think its Jitpack.io problem

**Comment by ludwig-pro** [comment]
I also have the same issue ! 

https://status.jitpack.io/ -> it seems that there is nothing special at jitpack

**Comment by rajeshmarotu** [comment]
I'm also facing the same issue without any code changes recently. I've tried updating package to its latest version 4.0.3, issue still persists.

**Comment by alexanderblackh** [comment]
Yeah, the issue is that Jitpack is down, https://status.jitpack.io is saying it's operational but it's clearly a lie, even their own home page isn't working. You can check other trackers such as https://github.com/jitpack/jitpack.io/issues/5337 or even Twitter to see people en masse are reporting these issue. 

We're stuck waiting for devs of library this to implement the dependency differently (ship it locally, from a separate repo, etc), or until Jitpack fixes it themselves. We have no choice but to wait.

**Comment by alexanderblackh** [comment]
@Titozzz, are you looking into a fix?

**Comment by wouterds** [comment]
I'm gonna close this issue as it is unrelated to this lib, can be tracked in Jitpack repo https://github.com/jitpack/jitpack.io/issues/5337

**Comment by jemishartoon** [comment]
Hello everyone, I've encountered this issue multiple times, so after extensive searching and checking various websites, I found a solution.

// Add Maven SciJava
maven { url = uri("https://maven.scijava.org/content/repositories/public/") }

on your build.gradle.kts

**Comment by Chaman-Viiva** [comment]
> Hello everyone, I've encountered this issue multiple times, so after extensive searching and checking various websites, I found a solution.
> 
> // Add Maven SciJava maven { url = uri("https://maven.scijava.org/content/repositories/public/") }
> 
> on your build.gradle.kts

I have tried this issue but still same error after cleaning gradlew for android,,
here is my error:
```
Could not determine the dependencies of task ':react-native-community_blur:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-community_blur:debugCompileClasspath'.
   > Could not find com.github.Dimezis:BlurView:version-2.0.3.
     Required by:
         project :react-native-community_blur
```

i am using version:
``` "@react-native-community/blur": "^4.3.2", ```

**Comment by hoangvuanhdevelopervn** [comment]
I have same issue when build pipe line for my project, seem this issue not fix
