### ISSUE TITLE
BlurView seems to affect the entire screen

### ISSUE THREAD

**Issue by FengZi-lv** [Kureev/react-native-blur#520]
```jsx
<View style={CommStyles.navigation_bar}>
                    <BlurView
                        style={CommStyles.navigation_bar}
                        blurType="xlight"
                        blurAmount={32}
                        reducedTransparencyFallbackColor="white"
                    />
                    <Image resizeMode='contain' style={CommStyles.navigation_head_image} source={require('../../Assets/Image/logo_nobg.png')} />
                    <Text style={CommStyles.navigator_title}>AAAAAAA</Text>
                </View>

var CommStyles =
    StyleSheet.create({
        navigation_bar: {
            width: '100%',
            height: 50,
            position: 'absolute',
            alignItems: 'center',
            flexDirection: 'row',
            top: 0,
            left: 0,
            bottom: 0,
            right: 0

        },
        navigation_head_image: {
            width: 34,
            height: 34,
            marginLeft: 10,
        },
        navigator_title: {
            fontSize: 24,
            marginLeft: 10,
            color: '#74583D',
            fontFamily: 'HYWenHei-85W',
        },
    });
```
When I use this code, the entire screen is covered in white

like this:
![image](https://user-images.githubusercontent.com/59948673/209468816-5342e0e0-b82b-4433-bdb6-86711315625f.png)

My `package.json` file, it's like this:
```json
{
  "name": "BenBenTNT",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/blur": "^4.3.0",
    "@react-native-community/image-editor": "^2.3.0",
    "@react-navigation/native": "^6.1.1",
    "@react-navigation/native-stack": "^6.9.7",
    "react": "18.1.0",
    "react-native": "0.70.6",
    "react-native-fs": "^2.20.0",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "0.72.3",
    "react-test-renderer": "18.1.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

What should I do? Thanks

**Comment by FengZi-lv** [comment]
When I'm not using it

**Comment by FengZi-lv** [comment]
When I'm not using it

![image](https://user-images.githubusercontent.com/59948673/209468923-a8454b15-a498-42c8-9fe6-589bc68de8e2.png)

**Comment by mxm87** [comment]
This stretches it to full screen:
`top: 0, left: 0, bottom: 0, right: 0`
remove `top: 0`

**Comment by metinaltinbas** [comment]
It is also the same for me. It works perfectly well on iOS but not on Android

**Comment by Adi52** [comment]
Adding `opacity: 0.99` to BlurView styles solved android problem in my case.

**Comment by lakhwinderdebut** [comment]
HI 

You are using position: absolute 

with these properties

top: 0,
left: 0,
bottom: 0,
 right: 0

when this style applied to a view it will cover the entire screen, that's why you are getting this

**Comment by abumubarak-dev** [comment]
Even without 

position: absolute
left: 0,
bottom: 0,
right: 0

it's still the same on android

**Comment by isotopeee** [comment]
Same issue I've encountered.

**Comment by Adi52** [comment]
In my case set props `overlayColor="transparent"` fixes it. After that you can add custom overlay view under blur. It's not perfect, but it works.

**Comment by metinaltinbas** [comment]
I added a style to parent view

`overflow: Platform.OS === 'android' ? 'hidden' : 'visible',`

and it is fixed.

**Comment by AronBe** [comment]
> In my case set props `overlayColor="transparent"` fixes it. After that you can add custom overlay view under blur. It's not perfect, but it works.

I implemented this fix and the problem in general disappears but for fresh Android install the dimmed colors show initially

**Comment by cospin** [comment]
Same issue here, fresh install RN 0.71.0 using BlurView as background on React Navigation BottomTab.
The `overflow` workaround worked for me.

**Comment by CodingWithNobody** [comment]
https://www.youtube.com/watch?v=qSlnZHPFxfk this will help
