### ISSUE TITLE
Blur without Image?

### ISSUE THREAD

**Issue by kujohn** [Kureev/react-native-blur#6]
Is it possible to blur based on the content of existing view and not an image?

**Comment by Kureev** [comment]
Sure, it doesn't matter what exactly you're gonna blur. It blurs every parent component

**Comment by kujohn** [comment]
Ah, it didn't work for me until @strazi notes that we need to add folder instead of add folder reference - https://github.com/Kureev/react-native-blur/issues/4#issuecomment-93735078

Thanks for the component!
